-- Copyright (c) 2022 Trevor Redfern
--
-- This software is released under the MIT License.
-- https://opensource.org/licenses/MIT

describe("moonpie.math.bresenham", function()
  local bresenham = require "moonpie.math.bresenham"

  it("yields a simple list of points", function()
    local iter = bresenham(1, 1, 5, 5)

    local x, y = iter()
    assert.equals(1, x)
    assert.equals(1, y)
    x, y = iter()
    assert.equals(2, x)
    assert.equals(2, y)
    x, y = iter()
    assert.equals(3, x)
    assert.equals(3, y)
    x, y = iter()
    assert.equals(4, x)
    assert.equals(4, y)
    x, y = iter()
    assert.equals(5, x)
    assert.equals(5, y)
    assert.is_nil(iter())
  end)

  it("some other test points", function()
    local iter = bresenham(1, 3, 7, 11)
    local x, y = iter()
    assert.equals(1, x)
    assert.equals(3, y)
    x, y = iter()
    assert.equals(2, x)
    assert.equals(4, y)
    x, y = iter()
    assert.equals(3, x)
    assert.equals(5, y)
    x, y = iter()
    assert.equals(3, x)
    assert.equals(6, y)
    x, y = iter()
    assert.equals(4, x)
    assert.equals(7, y)
    x, y = iter()
    assert.equals(5, x)
    assert.equals(8, y)
    x, y = iter()
    assert.equals(6, x)
    assert.equals(9, y)
    x, y = iter()
    assert.equals(6, x)
    assert.equals(10, y)
    x, y = iter()
    assert.equals(7, x)
    assert.equals(11, y)
  end)
end)